from tkinter import *
master = Tk()
Label(master, text='Custid').grid(row=0)
Label(master, text='Customer Name').grid(row=1)
Label(master, text='Branch').grid(row=2)
Label(master, text='account type').grid(row=3)
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
v = IntVar()
Radiobutton(master, text='Saving', variable=v, value=1).grid(row = 3, column = 1)
Radiobutton(master, text='Non saving', variable=v, value=2).grid(row = 3, column = 2)
w = Scale(master, from_=19, to=200, orient=HORIZONTAL)
Label(master, text='Amount').grid(row=4)
w.grid(row=4, column = 1)
insrt = Button(master, text = 'Insert', fg ='black')
insrt.grid(row=5)
updte = Button(master, text = 'Update', fg='black')
updte.grid(row=5,column=1)
dlte = Button(master, text ='Delete', fg ='black')
dlte.grid(row=6)
slct = Button(master, text ='Select', fg ='black')
slct.grid(row=6,column=1)
mainloop()



