from tkinter import *
master = Tk()
master.title("registration form")
master.config(background="light green")
Label(master, text='Form',bg="light green").grid(row=0,column=1) 
Label(master, text='Name',bg="light green").grid(row=1)
Label(master, text='Course',bg="light green").grid(row=2)
Label(master, text='Semester',bg="light green").grid(row=3)
Label(master, text='Form No',bg="light green").grid(row=4)
Label(master, text='Contact No',bg="light green").grid(row=5)
Label(master, text='Email id',bg="light green").grid(row=6)
Label(master, text='Address',bg="light green").grid(row=7)
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e6 = Entry(master)
e7 = Entry(master)
e1.grid(row=1, column=1)
e2.grid(row=2, column=1)
e3.grid(row=3, column=1)
e4.grid(row=4, column=1)
e5.grid(row=5, column=1)
e6.grid(row=6, column=1)
e7.grid(row=7, column=1)
submit = Button(master, text = 'Submit', fg ='black',bg="red")
submit.grid(row=8,column=1)
mainloop()

